### ISSUE TITLE
[Question] uTouchInjectionの導入条件に付いて。

### ISSUE THREAD

**Issue by gtk2k** [hecomi/uTouchInjection#1]
uTouchInjectionを開発中のuDDを使ったアプリに導入しようと思い、とりあえずLeft/Right HandAnchorにuDD_TouchDispacher.csをアタッチしてみたのですが、動作しませんでした。
uDesktopDuplication.TextureのRayCast()の冒頭に
```
var center = transform.position - transform.forward * r;
```
とありました。
もしかするとこれはuDDのサンプルのようにユーザー中心にして円上にuDDが並ぶ場合でしか動作しないものなのでしょうか？

**Comment by hecomi** [comment]
「動作しない」件につきましては、以下 2 点の切り分けが必要だと考えています。

1. `uDesktopDuplication.Texture.RayCast()` が所望の動作と異なる
2. そもそも uTouchInjection が動作しない

1 に関しましては、`r` は以下の `radius` を参照しており、付属のシェーダでスクリーンの曲げを設定した際の半径になります。同心円状の配置ではありません。

https://github.com/hecomi/uDesktopDuplication/blob/4ba7caf792659d715a61cdf0ef6c0b616cb3b4ff/Assets/uDesktopDuplication/Scripts/Texture.cs#L191-L195

また、付属の Prefab のようにスケール 1 時に 1 x 1 m のメッシュを想定しています。

2 に関しましては、付属のサンプルを実行してみていただき動作するかご確認頂けますでしょうか。

よろしくお願いいたします。

**Comment by gtk2k** [comment]
2です。
uTouchInjectionのサンプルは動作するのを確認しました。

スケールが問題のようですね。
ちなみにuDDがアタッチされているのはlocalScaleが (x:0.0576 y:1 z:0.0324) の親の配下にあるオブジェクトです。
解説ありがとうございました。
ちょっと調べてみます。
